#!/usr/bin/env sh

PLAYBOOK=${1:-main}
ENVIRONMENT=${2:-dev}
LOG_DIR=${3:-~/logs}
LOG_FILE=${3:-driver-server.log}
DATE=$(date '+%Y%m%d%H%M%S')

if [ ! -z ${LOG_DIR} ]; then
    mkdir -pv ${LOG_DIR}
fi
LOG_FILE=${LOG_DIR}/driver-windows.log

ansible-playbook  -i inventories/${ENVIRONMENT}/hosts ${PLAYBOOK}.yml | tee ${LOG_FILE}
